import type { ApplicationSurfaceItem } from './ApplicationsPage.types';

export const initialApplicationItems: ApplicationSurfaceItem[] = [
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    kind: 'managed',
    status: 'Ready',
    runtimeState: 'running',
    access: 'Private',
    backup: 'Protected',
    description: 'Password vault managed by this Project OS.',
    href: 'https://vault.example.test',
    iconUrl: '/app-images/vaultwarden.svg',
    lastEvent: 'Running normally',
  },
  {
    id: 'immich',
    name: 'Immich',
    kind: 'managed',
    status: 'Needs review',
    runtimeState: 'needs_attention',
    access: 'Private',
    backup: 'Needs backup',
    nextAction: {
      id: 'create_backup',
      label: 'Create backup',
      description: 'Create a backup before the next import.',
    },
    description: 'Photo library needs a backup before the next import.',
    href: 'https://photos.example.test',
    iconUrl: '/app-images/immich.svg',
    lastEvent: 'Backup protection needs review',
  },
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    kind: 'managed',
    status: 'Paused',
    runtimeState: 'paused',
    access: 'Local only',
    backup: 'Protected',
    nextAction: {
      id: 'start_app',
      label: 'Start app',
      description: 'Start the app so it can be opened again.',
    },
    description: 'Automation server is installed but currently paused.',
    href: 'http://localhost:8123',
    iconUrl: '/app-images/home-assistant.svg',
    lastEvent: 'Stopped by user',
  },
  {
    id: 'router-admin',
    name: 'Router Admin',
    kind: 'pinned',
    status: 'Pinned',
    runtimeState: 'shortcut',
    access: 'Open',
    backup: 'Not managed',
    description: 'Pinned shortcut. Project OS opens it but does not manage it.',
    href: 'http://192.168.1.1',
    lastEvent: 'Shortcut available',
  },
  {
    id: 'legacy-jellyfin',
    name: 'Jellyfin',
    kind: 'observed',
    status: 'Found',
    runtimeState: 'found',
    access: 'Local only',
    backup: 'Not managed',
    nextAction: {
      id: 'review_found_service',
      label: 'Review service',
      description: 'Decide whether to link, recover, or leave this service alone.',
    },
    description: 'Found on this machine. Not owned by this Project OS instance.',
    href: 'http://localhost:8096',
    iconUrl: '/app-images/jellyfin.svg',
    lastEvent: 'Found on this server',
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    kind: 'managed',
    status: 'Ready',
    runtimeState: 'running',
    access: 'Private',
    backup: 'Protected',
    description: 'Files, calendars, and collaboration hosted by this Project OS.',
    href: 'https://cloud.example.test',
    iconUrl: '/app-images/nextcloud.svg',
    lastEvent: 'Backup completed today',
  },
  {
    id: 'paperless-ngx',
    name: 'Paperless',
    kind: 'managed',
    status: 'Ready',
    runtimeState: 'running',
    access: 'Private',
    backup: 'Protected',
    description: 'Document archive with searchable scans and inbox processing.',
    href: 'https://paper.example.test',
    iconUrl: '/app-images/paperless-ngx.svg',
    lastEvent: 'Imported documents today',
  },
  {
    id: 'gitea',
    name: 'Gitea',
    kind: 'managed',
    status: 'Ready',
    runtimeState: 'running',
    access: 'Private',
    backup: 'Protected',
    description: 'Self-hosted git repositories and lightweight project tools.',
    href: 'https://git.example.test',
    iconUrl: '/app-images/gitea.svg',
    lastEvent: 'Running normally',
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    kind: 'managed',
    status: 'Needs review',
    runtimeState: 'needs_attention',
    access: 'Private',
    backup: 'Protected',
    nextAction: {
      id: 'review_found_service',
      label: 'Review alert',
      description: 'Review the monitor alert before Project OS marks this app healthy.',
    },
    description: 'Status monitor is running but has an alert that needs review.',
    href: 'https://status.example.test',
    iconUrl: '/app-images/uptime-kuma.svg',
    lastEvent: 'Monitor alert detected',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    kind: 'managed',
    status: 'Paused',
    runtimeState: 'paused',
    access: 'Local only',
    backup: 'Protected',
    nextAction: {
      id: 'start_app',
      label: 'Start app',
      description: 'Start dashboards so metrics can be viewed again.',
    },
    description: 'Metrics dashboards are installed but currently paused.',
    href: 'http://localhost:3000',
    iconUrl: '/app-images/grafana.svg',
    lastEvent: 'Stopped by user',
  },
  {
    id: 'syncthing',
    name: 'Syncthing',
    kind: 'managed',
    status: 'Ready',
    runtimeState: 'running',
    access: 'Local only',
    backup: 'Needs backup',
    nextAction: {
      id: 'create_backup',
      label: 'Create backup',
      description: 'Create a backup before changing synced folders.',
    },
    description: 'Device sync is running and should be backed up before folder changes.',
    href: 'http://localhost:8384',
    iconUrl: '/app-images/syncthing.svg',
    lastEvent: 'Folder sync active',
  },
  {
    id: 'actual-budget',
    name: 'Actual Budget',
    kind: 'pinned',
    status: 'Pinned',
    runtimeState: 'shortcut',
    access: 'Open',
    backup: 'Not managed',
    description: 'Pinned personal finance shortcut. Project OS does not manage it.',
    href: 'https://budget.example.test',
    iconUrl: '/app-images/actual-budget.svg',
    lastEvent: 'Shortcut available',
  },
  {
    id: 'homepage',
    name: 'Homepage',
    kind: 'pinned',
    status: 'Pinned',
    runtimeState: 'shortcut',
    access: 'Open',
    backup: 'Not managed',
    description: 'Pinned dashboard shortcut for server links and bookmarks.',
    href: 'https://home.example.test',
    iconUrl: '/app-images/homepage.svg',
    lastEvent: 'Shortcut available',
  },
  {
    id: 'found-pihole',
    name: 'Pi-hole',
    kind: 'observed',
    status: 'Found',
    runtimeState: 'found',
    access: 'Local only',
    backup: 'Not managed',
    nextAction: {
      id: 'review_found_service',
      label: 'Review service',
      description: 'Decide whether to link, recover, or leave this DNS service alone.',
    },
    description: 'Found on this machine. Not owned by this Project OS instance.',
    href: 'http://localhost/admin',
    iconUrl: '/app-images/pi-hole.svg',
    lastEvent: 'Found on this server',
  },
  {
    id: 'found-nginx-proxy-manager',
    name: 'Nginx Proxy Manager',
    kind: 'observed',
    status: 'Found',
    runtimeState: 'found',
    access: 'Local only',
    backup: 'Not managed',
    nextAction: {
      id: 'review_found_service',
      label: 'Review service',
      description: 'Review ownership before Project OS changes proxy routing.',
    },
    description: 'Found on this machine. Project OS is not managing this proxy.',
    href: 'http://localhost:81',
    iconUrl: '/app-images/nginx-proxy-manager.svg',
    lastEvent: 'Found on this server',
  },
];
