spring:
  application:
    name: autark-os-backend
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8082

autark-os:
  runtime-root: ../runtime/autark-os
  guardian:
    enabled: true
    initial-delay-ms: 10000
    interval-ms: 15000
  backups:
    scheduler:
      enabled: true
      initial-delay-ms: 30000
      interval-ms: 60000
